site_name: Wiki
site_description: Personal Notes of Dennis Irsigler.
site_author: Dennis Irsigler
site_url: https://wiki.irsigler.cloud
repo_url: https://github.com/dirsigler/wiki
repo_name: "dirsigler/wiki"
edit_uri: ""

# Fail to build if we have broken links
strict: false

# Copyright
copyright: 'Copyright &copy; 2022 Dennis Irsigler'

theme:
  name: material
  icon:
    logo: material/library
    repo: fontawesome/brands/git-alt
  language: en
  favicon: images/favicon.png
  palette:
    primary: blue
    accent: indigo
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - search.highlight
    - header.autohide
  font:
    text: 'Roboto'
    code: 'Cascadia Code PL'

# Plugins
plugins:
  - search
  - autolinks
  - markmap
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true
  - git-revision-date

markdown_extensions:
  - meta
  - def_list
  - attr_list
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - 'stylesheets/extra.css'

extra:
  generator: true
  social:
    - icon: fontawesome/solid/earth-europe
      link: https://irsigler.dev
    - icon: fontawesome/brands/github
      link: https://github.com/dirsigler
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dirsigler

nav:
  - Home: index.md
  - Docs:
      - Overview: docs/index.md
